version: "3"
services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL}
        volumes:
            - ./dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - puma-network
    notify-microservice:
        container_name: notify-microservice
        environment:
            ENVIRONMENT: dev
        build:
            context: ../${NOTIFY_PATH}/
            dockerfile: dev.Dockerfile
        ports:
            - "3003:3003"
        depends_on:
            - db
        volumes:
            - ../${NOTIFY_PATH}:/app
            - /app/node_modules
        networks:
            - puma-network

networks:
    puma-network:   